
services:
  api:
    container_name: loan_api
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - '8000:8000'
    env_file:
      - ./.env.dev
    depends_on:
      - database
  database:
    container_name: loan_db
    image: postgres:17.4
    ports:
      - '6000:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.db

volumes:
  postgres_data: